name: Prettier Check

on:
  pull_request:
    branches:
      - main

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run Prettier
        run: yarn prettier --check
