name: Test Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Enable Corepack
        run: npx corepack enable

      - name: Run install
        uses: borales/actions-yarn@v5.0.0
        with:
          cmd: install # will run `yarn install` command

      - name: Build production bundle
        uses: borales/actions-yarn@v5.0.0
        with:
          cmd: build # will run `yarn build` command
