name: Test Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn run build